import {NAME} from './constants';

export const FETCH_STATISTICS = `${NAME}/FETCH_STATISTICS`;
export const FETCH_STATISTICS_SUCCESS = `${NAME}/FETCH_STATISTICS_SUCCESS`;
export const FETCH_STATISTICS_FAILURE = `${NAME}/FETCH_STATISTICS_FAILURE`;